version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    networks:
      - local
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - local
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express
    networks:
      - local
    restart: always
    ports:
      - '8081:8081'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - local
    ports: 
      - '5432:5432'
    volumes:
      - addressbook-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    networks:
      - local
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    
  addressbook:
    build:
      context: ./addressbook
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - local

volumes:
  addressbook-data:
  mongo-data:

networks:
  local: